# Generated by Django 3.2.5 on 2021-08-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20210813_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(default='/Users/lateefa/Desktop/code/django/lateeflab/staticfiles/blog1.png', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
