# Generated by Django 3.2.5 on 2021-08-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_blogpost_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(default='uploads/blog1.jpg', upload_to='uploads/coverimages'),
        ),
    ]
