# Generated by Django 3.2.5 on 2022-04-08 20:32

from django.db import migrations, models
import lateeflab.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_alter_blogpost_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='cover_image',
            field=models.ImageField(default='uploads/blog1.jpg', storage=lateeflab.storage_backends.PublicMediaStorage(), upload_to='uploads/coverimages'),
        ),
    ]
